# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
      kernelModules = [];
    };
    kernelModules = ["kvm-amd"];
    kernelParams = ["nvidia_drm.fbdev=1"];
    extraModulePackages = [];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f7077956-f780-474f-bd4b-23306f821fe1";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5CDC-71DC";
    fsType = "vfat";
  };
  # Mounting 7200 1tb btrfs HDD
  fileSystems."/home/lukasd/Music" = {
    device = "/dev/disk/by-uuid/60f1efae-e1ee-4814-8342-f8b02498627e";
    fsType = "btrfs";
    options = ["subvol=Music" "compress=zstd" "noatime"];
  };
  fileSystems."/home/lukasd/Games" = {
    device = "/dev/disk/by-uuid/60f1efae-e1ee-4814-8342-f8b02498627e";
    fsType = "btrfs";
    options = ["subvol=Games" "compress=zstd" "noatime"];
  };
  fileSystems."/home/lukasd/Downloads" = {
    device = "/dev/disk/by-uuid/60f1efae-e1ee-4814-8342-f8b02498627e";
    fsType = "btrfs";
    options = ["subvol=Downloads" "compress=zstd" "noatime"];
  };
  fileSystems."/home/lukasd/Documents" = {
    device = "/dev/disk/by-uuid/60f1efae-e1ee-4814-8342-f8b02498627e";
    fsType = "btrfs";
    options = ["subvol=Documents" "compress=zstd" "noatime"];
  };
  fileSystems."/home/lukasd/Pictures" = {
    device = "/dev/disk/by-uuid/60f1efae-e1ee-4814-8342-f8b02498627e";
    fsType = "btrfs";
    options = ["subvol=Pictures" "compress=zstd" "noatime"];
  };
  fileSystems."/home/lukasd/Videos" = {
    device = "/dev/disk/by-uuid/60f1efae-e1ee-4814-8342-f8b02498627e";
    fsType = "btrfs";
    options = ["subvol=Videos" "compress=zstd" "noatime"];
  };
  # mounting small 1tb hdd
  fileSystems."/home/lukasd/Files" = {
    device = "/dev/disk/by-uuid/fb2e81d8-dca5-4288-b903-813897b1a4ea";
    fsType = "btrfs";
    options = ["subvol=Files" "compress=zstd" "noatime"];
  };
  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp30s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
